### ISSUE TITLE
No Device Trackers created after install

### ISSUE THREAD

**Issue by jinglyjangles** [RobertD502/home-assistant-whistle#7]
After installing via HACS only sensor.whistle_ody_event are created. 2/4 of these are the Whistle Health & GPS (Whistle Go's) with the other 2 being Health's. 

![image](https://user-images.githubusercontent.com/37057401/178359470-50fd849a-143c-405d-bdea-4aec3e9252e2.png)

**Comment by RobertD502** [comment]
Just to confirm, you are able to see GPS coordinates within the whistle app for the two Go explore devices?

**Comment by jinglyjangles** [comment]
Hmm, I can see the 2 Go's on the map and start the tracking feature. But I haven't found a sub menu that shows me the GPS coordinates themselves.

**Comment by jinglyjangles** [comment]
Any chance you have a postman collection built out? Happy to post results/do some testing.

**Comment by jinglyjangles** [comment]
Shoved the pywhistle library into pycharm, dogs have have a ddress listed but not a lat/lon in the main blob. The address blob does have lat/lon though.

**Comment by RobertD502** [comment]
Ah great I was just about to create a test file for you to run with the library.  The two health devices are returning 'None' for last location as expected.

However, for the two GPS devices, are latitude and longitude listed within last_location?

**Comment by jinglyjangles** [comment]
Yep, here is the relevant blob with pii redacted. 
`'last_location': {'latitude': X, 'longitude':Y, 'timestamp': '2022-07-11T20:17:36Z', 'uncertainty_meters': 0.0, 'reason': 'back_in_beacon', 'place': {'distance': 0, 'distance_units': 'feet', 'id': X, 'status': 'in_beacon_range', 'units': 'feet'}, 'description': {'address': 'X', 'place': 'TOWN', 'postcode': 'X', 'region': 'X', 'country': 'United States'}}`

**Comment by jinglyjangles** [comment]
For the other 2 I'll probably write an automation to change location state when I see them off the network. i.e. not home

**Comment by jinglyjangles** [comment]
Yep! It created the two for the GPS based ones. Drat so it looks like the Health ones only do BLE no wifi, thoughts on still shoving the others in with coords 0,0 for the time being? I'll have to add presence detection via BLE but then I can override the states manually.

**Comment by jinglyjangles** [comment]
Quickly threw this together this AM; https://github.com/RobertD502/home-assistant-whistle/pull/8/files let me know your thoughts

**Comment by jhansche** [comment]
I would like to add my "second" for splitting the device/entities. The Whistle Fit (now Whistle Health) devices have a bunch of the data currently saved as attributes of the device_tracker; but that won't be created because they don't have GPS. Would love to have everything else minus GPS.

Is there an issue or PR or WIP branch we can follow for progress?

**Comment by RobertD502** [comment]
I'll be honest, it won't be for quite a while since I have a lot of other things going on right now.

I'd need to be added to an account that has a Fit in order to determine what Whistle's servers return.

**Comment by jhansche** [comment]
Understood. I'll do some research on my own and see what I can do to get a PR up.

Do you have some goals that I should keep in mind? Assuming:

* Each Whistle is one device
  * device_tracker created if has_gps
  * non-location values currently set as device_tracker attributes split out into individual entities
  * keep sensor as is? or convert to event?

**Comment by RobertD502** [comment]
The integration currently uses a library written by someone else. As part of the update, I plan on writing a new library that can be used in an easier manner within home assistant - use a coordinator to fetch all device updates from a single endpoint with the library instead of calling the update method for every device. 

Once that is done, I'll be rewriting the entire integration, so, any PRs are unlikely to work as they won't account for the new library. I really do appreciate the offer though!

Getting added to the account will make the process a lot easier especially when it comes to creating the integration. Do you mind if I tag you in this issue when I'm ready for it?

**Comment by jhansche** [comment]
Sure, feel free.

**Comment by RobertD502** [comment]
Hi @jhansche,

I'm in the middle of writing the backend right now...would you be able to add my email to the account?

**Comment by jhansche** [comment]
Yes, I'll get that setup tonight, when I get back home!

**Comment by RobertD502** [comment]
You can email me at flairhass at gmail dot com (email I use for another integration) and then I'll send you my personal email that I use for Whistle.
